// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDb3YHIIHstyON8h_6Z5DZZgKWIiZD9-Xo',
    appId: '1:1003280727040:web:e564a3c1df1c81de31ece5',
    messagingSenderId: '1003280727040',
    projectId: 'ridealong-9de6b',
    authDomain: 'ridealong-9de6b.firebaseapp.com',
    storageBucket: 'ridealong-9de6b.appspot.com',
    measurementId: 'G-1C8X6744WR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL3rvvz0uQ5Yat2ogt4XAbUAVCeLOx3UA',
    appId: '1:1003280727040:android:15580d4422cfc17031ece5',
    messagingSenderId: '1003280727040',
    projectId: 'ridealong-9de6b',
    storageBucket: 'ridealong-9de6b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi4zAXbvAzz3P6SdfKTZixpCejcz20Jtk',
    appId: '1:1003280727040:ios:41efd2b9c2dc479c31ece5',
    messagingSenderId: '1003280727040',
    projectId: 'ridealong-9de6b',
    storageBucket: 'ridealong-9de6b.appspot.com',
    iosClientId: '1003280727040-2c23nkkssuvjc4ajtrghi4tg92jrsvo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.rideAlong',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi4zAXbvAzz3P6SdfKTZixpCejcz20Jtk',
    appId: '1:1003280727040:ios:41efd2b9c2dc479c31ece5',
    messagingSenderId: '1003280727040',
    projectId: 'ridealong-9de6b',
    storageBucket: 'ridealong-9de6b.appspot.com',
    iosClientId: '1003280727040-2c23nkkssuvjc4ajtrghi4tg92jrsvo0.apps.googleusercontent.com',
    iosBundleId: 'com.example.rideAlong',
  );
}
